//
//  UUIImage+TransferImageData.h
//
//  Created by HW on 2020/4/10.
//

#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

@interface UIImage (TransferImageData)

#pragma  mark-UIImage image and byte data conversion

/// Get ARGB data, the memory is managed by the outside, need to delete
/// @return byte data in image ARGB format
- (unsigned char *)transferToARGBData;

/// Get the data of RGBA, the memory is managed externally and needs to delete
/// @return byte data in image RGBA format
- (unsigned char *)transferToRGBAData;

/// Get Gray's data, the memory is managed externally and needs to delete
/// @return Byte data in image Gray format
- (unsigned char *)transferToGrayData;

/// Convert ARGB byte data to UIImage
/// @param data byte data in image ARGB format
/// @param size image size
/// UIImage generated by @return
+ (UIImage *)transferToImageWithARGBData:(unsigned char *)data withSize:(CGSize)size;

/// Convert ARGB byte data to UIImage
/// @param data byte data in image ARGB format
/// @param width image width
/// @param width image height
/// UIImage generated by @return
+ (UIImage *)transferToImageWithARGBData:(unsigned char *)data withWidth:(int)width withHeight:(int)height;

/// Convert RGBA byte data to UIImage
/// @param data byte data in image RGBA format
/// @param size image size
/// UIImage generated by @return
+ (UIImage *)transferToImageWithRGBAData:(unsigned char *) data withSize:(CGSize) size;

/// Convert RGBA byte data to UIImage
/// @param data byte data in image RGBA format
/// @param width image width
/// @param width image height
/// UIImage generated by @return
+ (UIImage *)transferToImageWithRGBAData:(unsigned char *)data withWidth:(int)width withHeight:(int)height;

/// Convert Gray byte data to UIImage
/// @param data byte data in image Gray format
/// @param size image size
/// UIImage generated by @return
+ (UIImage *)transferToImageWithGrayData:(unsigned char *)data withSize:(CGSize)size;

/// Convert Gray byte data to UIImage
/// @param data byte data in image Gray format
/// @param width image width
/// @param width image height
/// UIImage generated by @return
+ (UIImage *)transferToImageWithGrayData:(unsigned char *)data withWidth:(int)width withHeight:(int)height;

@end

NS_ASSUME_NONNULL_END
